ppipeline improvements

diff --git a/twig_module/twig-do-your-job b/twig_module/twig-do-your-job
--- a/twig_module/twig-do-your-job
+++ b/twig_module/twig-do-your-job
@@ -1,11 +1,20 @@
 #!/bin/bash
 
-TIMESTAMP=$(date +"%Y-%m-%d"_%H-%M-%S)
-RUN_ID="twig_default_job_$TIMESTAMP"
-STDOUT_DIR="/workspace/output/models/$RUN_ID.txt"
+RUN_ID=$(/workspace/twig_module/get_value.py --yaml_file /workspace/twig_module/TwigJob.yml --item run_id)
+OUT_FILE=/workspace/output/models/$RUN_ID.std_out
+ERR_FILE=/workspace/output/models/$RUN_ID.std_err
 
-/workspace/twig_module/twig.py --do_your_job /workspace/twig_module/TwigJob.yml > $STDOUT_DIR
+if [[ -f  $OUT_FILE ]]
+then
+    echo "ERROR: $OUT_FILE already exists, stopping"
+    exit 1
+fi
 
-END_TIME=$(date +"%Y-%m-%d"_%H-%M-%S)
-echo "Ended at $END_TIME"
-exit 0
+if [[ -d /workspace/output/models/$RUN_ID ]]
+then
+    echo "ERROR: /workspace/output/models/$RUN_ID already exists, stopping"
+    exit 1
+fi
+
+cp /workspace/twig_module/TwigJob.yml /workspace/output/models/$RUN_ID.TwigJob.yml
+time /workspace/twig_module/twig.py --do_your_job /workspace/twig_module/TwigJob.yml > $OUT_FILE 2> $ERR_FILE
